ktor {
  deployment {
    port = 8080
    host = "0.0.0.0"
  }

  application {
    modules = [ com.fcosta.ApplicationKt.module ]
  }

  mongo {
    dev {
      uri = "mongodb+srv://fcosta1188:m3tr0n0v4-883311@metronova-cluster-dev.smbjvzb.mongodb.net/?retryWrites=true&w=majority&appName=metronova-cluster-dev"
      database = "users"
    }
    prod {
      uri = "mongodb+srv://prodUser:prodPassword@cluster0.mongodb.net/prodDb"
      database = "users"
    }
  }

  logging {
    level = "INFO"
  }
}
